# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [97]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
from sklearn.datasets import load_diabetes
import numpy as np
from sklearn.model_selection import train_test_split as tts

# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function.

In [33]:
help(load_diabetes)

Help on function load_diabetes in module sklearn.datasets._base:

load_diabetes(*, return_X_y=False, as_frame=False)
    Load and return the diabetes dataset (regression).
    
    ==============   ==================
    Samples total    442
    Dimensionality   10
    Features         real, -.2 < x < .2
    Targets          integer 25 - 346
    ==============   ==================
    
    Read more in the :ref:`User Guide <diabetes_dataset>`.
    
    Parameters
    ----------
    return_X_y : bool, default=False.
        If True, returns ``(data, target)`` instead of a Bunch object.
        See below for more information about the `data` and `target` object.
    
        .. versionadded:: 0.18
    
    as_frame : bool, default=False
        If True, the data is a pandas DataFrame including columns with
        appropriate dtypes (numeric). The target is
        a pandas DataFrame or Series depending on the number of target columns.
        If `return_X_y` is True, then (`data`, `targ

In [104]:
diabetes = load_diabetes(return_X_y=False, as_frame=True)

Let's explore this variable by looking at the different attributes. Do this by looking at the `keys()` of this variable.

In [105]:
diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])

The next step is to read the description of the dataset. Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable

In [106]:
diabetes.DESCR

'.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - age     age in years\n      - sex\n      - bmi     body mass index\n      - bp      average blood pressure\n      - s1      tc, T-Cells (a type of white blood cells)\n      - s2      ldl, low-density lipoproteins\n      - s3      hdl, high-density lipoproteins\n      - s4      tch, thyroid stimulating hormone\n      - s5      ltg, lamotrigine\n      - s6      glu, blood sugar level\n\nNo

What are the variables in this dataset according to the description? List them in the markdown cell below

#### Enter your answer here:

According to the description:
- age
- sex 
- body 
- mass index
- average blood pressure 
- and six blood serum measurements

Now explore the data. Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). In the cell below find the shape of the numpy array contained in the data portion of the diabetes variable.

In [107]:
y = diabetes.target
y.shape

(442,)

In [110]:
X = diabetes.frame
X

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019908 -0.017646   151.0  
1   -0.039493 -0.068330 -0.092204    75.0  
2   -0.002592  0.002864 -0.025930   141.0  
3    0.034309  0.022692 -0.009362   206.0  
4   -0.002592 -0.031991 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018118  0.044485   104.0  
439 -0.011080 -0.046879  0.015491   132.0  
440  0.026560  0.044528 -0.025930   220.0  
441 -0.039493 -0.004220  0.003064    57.0  

[442 rows x 11 columns]

In [129]:
X.columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6',
       'target'],
      dtype='object')

# Challenge 2 - Perform Supervised Learning on the Dataset

#### The data has already been split to predictor and response variables. The response variable is in the `target` portion of the variable. 

Given this information, let's apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset. In the cell below, import the linear regression class from sklearn. 

In [117]:
from sklearn.linear_model import LinearRegression as LinReg
linreg=LinReg()

Initialize the model in the variable `diabetes_model`

In [111]:
X_train, X_test, y_train, y_test = tts(X,y, test_size=0.2)

In the cell below, fit the model and print the intercept and coefficients of the model. 

In [119]:
linreg.fit(X_train, y_train)

LinearRegression()

In [120]:
linreg.coef_

array([ 2.30334482e-13, -1.22534024e-13, -7.35745605e-13, -2.27066673e-13,
        6.86052377e-13, -5.08089469e-13, -4.58275602e-13,  3.90060721e-14,
       -3.88176610e-13, -3.98710460e-14,  1.00000000e+00])

In [121]:
linreg.intercept_

0.0

# Bonus Challenge 1 - Conduct a Hypothesis Test on the Model

Once we have generated a linear model, we can test each coefficient using a t-test to see whether the confidence interval for the variable contains zero. We can also perform an overall F test to check whether at least one coefficient is significantly different from zero. 

Refer to the resource in this [link](https://onlinecourses.science.psu.edu/stat501/node/297/) for more details and perform the t-tests for the model above. Additionally, interpret the results and list coefficients are significantly different from zero.


Hint: use the statsmodels package.

Your result should look similar to this:

![ols](../ols-results.png)

In [131]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [135]:
results = smf.ols("target ~ age + sex + bmi + bp + s1 + s2 + s3 + s4 + s5 + s6", data = X).fit()
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                 target   R-squared:                       0.518
Model:                            OLS   Adj. R-squared:                  0.507
Method:                 Least Squares   F-statistic:                     46.27
Date:                Tue, 30 Nov 2021   Prob (F-statistic):           3.83e-62
Time:                        17:00:37   Log-Likelihood:                -2386.0
No. Observations:                 442   AIC:                             4794.
Df Residuals:                     431   BIC:                             4839.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    152.1335      2.576     59.061      0.0

# Challenge 2 - Peform Supervised Learning on a Pandas Dataframe

Now that we have looked at data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [223]:
auto = pd.read_csv('../auto-mpg.csv')

Look at the first 5 rows using the `head()` function:

In [224]:
auto.head()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [225]:
auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horse_power   392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   car_name      398 non-null    object 
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB


In [227]:
auto.mpg = auto.mpg.astype(int)

In [228]:
auto.displacement = auto.displacement.astype(int)

In [230]:
auto.acceleration = auto.acceleration.astype(int)

In [231]:
auto.replace([np.inf, -np.inf], np.nan, inplace=True)

In [236]:
(auto.isna()).sum()

mpg             0
cylinders       0
displacement    0
horse_power     0
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

In [235]:
auto.dropna(inplace=True)

In [237]:
auto.horse_power = auto.horse_power.astype(int)

What is the newest model year and the oldest model year?

In [207]:
print(auto['model_year'].max())
print(auto['model_year'].min())

82
70


Check the dataset for missing values and remove all rows containing at least one missing value.

In [238]:
# Done above

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [239]:
auto.cylinders.value_counts()

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

In [240]:
auto = auto.drop("car_name", axis=1)

In [258]:
y = auto.mpg
X = auto.drop('mpg', axis=1)

Now we will the dataset that we processed and peform linear regression on this data to predict the mpg for each vehicle. Initialize the model in the cell below.

In [259]:
X_a_train, X_a_test, y_a_train, y_a_test = tts(X,y, test_size=0.2)

In [293]:
test = linreg.fit(X_a_train, y_a_train)

In [261]:
X_a_test.shape

(79, 6)

In [294]:
y_pred = test.redict(X_a_test)

Next, fit the model in the cell below.

In [295]:
y_pred

array([28.09899015, 15.06000276, 23.45619197, 26.13432403, 17.15757433,
       31.63083025, 22.13304129, 16.49882167, 29.29954699, 23.99054455,
       27.39949923, 24.62394829, 13.83811896, 26.55094733, 13.88087572,
        8.29328222, 10.61769364, 31.61752248, 19.27646118, 19.89392629,
       26.70915472, 20.77794923, 12.18499108, 17.52683716, 19.84457147,
       17.9929018 , 31.25813678, 28.40846271, 17.57824491, 27.92760947,
       19.99634287, 16.06694781, 29.44655036, 23.9476749 , 27.44390357,
       17.89543148, 17.86073093, 26.27367719, 19.76615157, 15.97903788,
       20.00378178, 10.31266831, 29.47903073, 23.04556982, 26.29368689,
       22.41618281, 16.93885116, 19.7716715 , 19.3708435 , 19.01882525,
       26.2336646 , 27.02284285, 19.14322058, 34.0553926 , 16.22080694,
       26.5959607 , 25.49019697, 15.11031447, 31.5018178 , 29.21030035,
       26.59439591, 34.65023448, 27.77566928, 23.94717785, 31.31877765,
       24.6590578 , 13.93680401, 15.48538526, 28.327113  , 24.72

# Challenge 3 - Evaluate the Model

the r squared score of a model tells us how much variation is explained by the model. In a typical dataset, most observations differ from the mean. When we create a model, we are trying to generate an equation that will tell us by how much each observation will differ from the mean. Obviously, the vast majority of models are not perfect. They can only predict some of the variation from the mean but not all of it. We attribute the rest of the difference between the actual value and the mean to random error. We would like random error to explain the as little as possible of the variation. This is why the r squared score is an important metric.

In the next cell, compute the r squared score of the model. Do this by first computing the predicted values and assign them to `y_pred`.

In [299]:
from sklearn import metrics

In [300]:
r2 = metrics.r2_score(y_a_test, y_pred)

In [301]:
r2

0.7739189609211942

#### Our next step is to evaluate the model using the test data. We would like to ensure that our model is not overfitting the data. This means that our model will not be able to generalize well outside of the training data.

In the cell below, use the model to generate the predicted values for the training data and assign them to `y_test_pred`. Compute the r squared score for the test data by comparing the oberserved `y_test` data and the predicted `y_test_pred`.

In [296]:
y_test_pred = linreg.predict(X_a_train)
y_test_pred[0:10]

array([31.85064862, 32.06797279,  7.37105967, 26.81619447, 11.57756371,
       26.00118637, 11.08270022, 15.22610353, 29.94412241, 15.45867265])

In [297]:
y_test = linreg.predict(X_a_test)
y_test[0:10]

array([28.09899015, 15.06000276, 23.45619197, 26.13432403, 17.15757433,
       31.63083025, 22.13304129, 16.49882167, 29.29954699, 23.99054455])

In [298]:
r2_b = metrics.r2_score(y_test, y_pred)
r2_b

1.0

Yes, there is overfitting.

# Challenge 4 - Improve the Model Fit

While the most common way to improve the fit of a model is by using regularization, there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [302]:
X_train09, X_test09, y_train09, y_test09 = tts(X,y, test_size=0.1)

Initialize a new model. Name this model `auto_model09`. Fit the model to the new sample data.

In [303]:
auto_model09 = linreg.fit(X_train09, y_train09)

Compute the predicted values and r squared score for our new model and new sample data.

In [304]:
y_pred09 = auto_model09.predict(X_test09)
y_pred09

array([26.97360953, 34.81076999, 21.64865382,  9.92697334, 28.90654827,
       18.16143583, 18.00459601, 19.5243408 , 31.91776444, 26.6699375 ,
       23.76640538, 21.01865725, 24.62640623, 11.45473222, 27.47176475,
       14.88759757, 25.87346451, 23.81407231, 19.44580435, 27.38427042,
       31.72755223, 22.8809022 , 28.72523939, 26.64334436, 11.92909011,
       24.1805903 , 11.7292679 , 12.60137032, 22.25537057, 18.19529834,
       11.3806594 , 31.17427217, 12.15707395, 21.74132836, 22.47953266,
       23.09358972, 26.30690989, 31.43339718, 20.39604629, 20.78260678])

In [305]:
r2_09 = metrics.r2_score(y_test09, y_pred09)
r2_09

0.8175836297292274

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

Yes, the r squared is quite higher than before.

# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

In [286]:
from sklearn.datasets import make_friedman1
from sklearn.feature_selection import RFE
from sklearn.svm import SVR

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

Fit the model and print the ranking

In [306]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=3)
auto_model = selector.fit(X, y)

In [313]:
y_pred = auto_model.predict(X)

In [315]:
r2_exp = metrics.r2_score(y_pred, y)
r2_exp

0.5425331809196015

Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [321]:
auto.head(1)

mpg  cylinders  displacement  horse_power  weight  acceleration  model_year
0   18          8           307          130    3504            12          70

In [324]:
auto_reduced = auto.drop(columns=['mpg', 'weight', 'acceleration', 'model_year'])

In [325]:
X = auto_reduced

In [326]:
X_train_reduced, X_test_reduced, y_train_reduced, y_test_reduced = tts(X,y, test_size=0.2)

Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [327]:
auto_model_reduced = selector.fit(X, y)

In [328]:
y_pred_reduced = auto_model_reduced.predict(X)

In [329]:
r2_train_reduced = metrics.r2_score(y_pred_reduced, y)
r2_train_reduced

0.45081551748374105

No, there is no improvement.