# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [1]:
# Import your libraries:
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LinearRegression as LinReg

# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function.

In [2]:
help(load_diabetes)


Help on function load_diabetes in module sklearn.datasets._base:

load_diabetes(*, return_X_y=False, as_frame=False)
    Load and return the diabetes dataset (regression).
    
    ==============   ==================
    Samples total    442
    Dimensionality   10
    Features         real, -.2 < x < .2
    Targets          integer 25 - 346
    ==============   ==================
    
    .. note::
       The meaning of each feature (i.e. `feature_names`) might be unclear
       (especially for `ltg`) as the documentation of the original dataset is
       not explicit. We provide information that seems correct in regard with
       the scientific literature in this field of research.
    
    Read more in the :ref:`User Guide <diabetes_dataset>`.
    
    Parameters
    ----------
    return_X_y : bool, default=False.
        If True, returns ``(data, target)`` instead of a Bunch object.
        See below for more information about the `data` and `target` object.
    
        .. versi

In [3]:
diabetes = pd.DataFrame(load_diabetes().data, columns=load_diabetes().feature_names)

In [4]:
diabetes.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204  
2 -0.002592  0.002864 -0.025930  
3  0.034309  0.022692 -0.009362  
4 -0.002592 -0.031991 -0.046641

Let's explore this variable by looking at the different attributes. Do this by looking at the `keys()` of this variable.

In [5]:
# Your code here:
diabetes.keys()


Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')

In [6]:
diabetes["PROG"] = load_diabetes().target #Variable objetivo 

In [7]:
diabetes.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6   PROG  
0 -0.002592  0.019908 -0.017646  151.0  
1 -0.039493 -0.068330 -0.092204   75.0  
2 -0.002592  0.002864 -0.025930  141.0  
3  0.034309  0.022692 -0.009362  206.0  
4 -0.002592 -0.031991 -0.046641  135.0

The next step is to read the description of the dataset. Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable

In [8]:
data = load_diabetes()
print(data.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

What are the variables in this dataset according to the description? List them in the markdown cell below

#### Enter your answer here:




Now explore the data. Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). In the cell below find the shape of the numpy array contained in the data portion of the diabetes variable.

In [9]:
diabetes.shape

(442, 11)

In [10]:
X = diabetes.drop("PROG", axis=1)
X.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204  
2 -0.002592  0.002864 -0.025930  
3  0.034309  0.022692 -0.009362  
4 -0.002592 -0.031991 -0.046641

In [11]:
y = diabetes.PROG
y.head()

0    151.0
1     75.0
2    141.0
3    206.0
4    135.0
Name: PROG, dtype: float64

In [12]:
X.shape

(442, 10)

In [13]:
y.shape

(442,)

# Challenge 2 - Perform Supervised Learning on the Dataset

#### The data has already been split to predictor and response variables. The response variable is in the `target` portion of the variable. 

Given this information, let's apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset. In the cell below, import the linear regression class from sklearn. 

In [14]:
X_train, X_test, y_train, y_test = tts(X,y, test_size=0.2)

Initialize the model in the variable `diabetes_model`

In [15]:
linreg = LinReg()

In [16]:
linreg

LinearRegression()

In the cell below, fit the model and print the intercept and coefficients of the model. 

In [17]:
linreg.fit(X_train, y_train)

LinearRegression()

In [18]:
linreg.coef_ 

array([   7.01490494, -229.56612711,  512.78352057,  350.08851048,
       -916.69891902,  578.05091883,  160.28628422,  116.1512553 ,
        810.95147728,   26.91897876])

In [19]:
linreg.intercept_

153.3611201497729

In [20]:
y_pred = linreg.predict(X_test)

In [21]:
y_pred.shape

(89,)

# Bonus Challenge 1 - Conduct a Hypothesis Test on the Model

Once we have generated a linear model, we can test each coefficient using a t-test to see whether the confidence interval for the variable contains zero. We can also perform an overall F test to check whether at least one coefficient is significantly different from zero. 

Refer to the resource in this [link](https://onlinecourses.science.psu.edu/stat501/node/297/) for more details and perform the t-tests for the model above. Additionally, interpret the results and list coefficients are significantly different from zero.


Hint: use the statsmodels package.

Your result should look similar to this:

![ols](../ols-results.png)

In [22]:
# Your code here:



# Challenge 2 - Peform Supervised Learning on a Pandas Dataframe

Now that we have looked at data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [23]:
auto = pd.read_csv('../auto-mpg.csv')

Look at the first 5 rows using the `head()` function:

In [24]:
auto.head()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [25]:
auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horse_power   392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   car_name      398 non-null    object 
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB


What is the newest model year and the oldest model year?

In [26]:
auto.model_year.max() #newest model year

82

In [27]:
auto.model_year.min() #oldest model year

70

Check the dataset for missing values and remove all rows containing at least one missing value.

In [28]:
auto.isnull()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0    False      False         False        False   False         False   
1    False      False         False        False   False         False   
2    False      False         False        False   False         False   
3    False      False         False        False   False         False   
4    False      False         False        False   False         False   
..     ...        ...           ...          ...     ...           ...   
393  False      False         False        False   False         False   
394  False      False         False        False   False         False   
395  False      False         False        False   False         False   
396  False      False         False        False   False         False   
397  False      False         False        False   False         False   

     model_year  car_name  
0         False     False  
1         False     False  
2         False     False  
3         False     False  
4         False     False  
..          ...       ...  
393       False     False  
394       False     False  
395       False     False  
396       False     False  
397       False     False  

[398 rows x 8 columns]

In [29]:
auto = auto.dropna()
auto

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0    18.0          8         307.0        130.0    3504          12.0   
1    15.0          8         350.0        165.0    3693          11.5   
2    18.0          8         318.0        150.0    3436          11.0   
3    16.0          8         304.0        150.0    3433          12.0   
4    17.0          8         302.0        140.0    3449          10.5   
..    ...        ...           ...          ...     ...           ...   
393  27.0          4         140.0         86.0    2790          15.6   
394  44.0          4          97.0         52.0    2130          24.6   
395  32.0          4         135.0         84.0    2295          11.6   
396  28.0          4         120.0         79.0    2625          18.6   
397  31.0          4         119.0         82.0    2720          19.4   

     model_year                       car_name  
0            70  \t"chevrolet chevelle malibu"  
1            70          \t"buick skylark 320"  
2            70         \t"plymouth satellite"  
3            70              \t"amc rebel sst"  
4            70                \t"ford torino"  
..          ...                            ...  
393          82            \t"ford mustang gl"  
394          82                  \t"vw pickup"  
395          82              \t"dodge rampage"  
396          82                \t"ford ranger"  
397          82                 \t"chevy s-10"  

[392 rows x 8 columns]

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [51]:
auto.cylinders.value_counts() #There are 5 possible values of cylinders

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

Queremos generar un modelo de regresión lineal que prediga el mpg. Para ello, primero elimine la columna car_name, ya que no contiene ningún dato cuantitativo. A continuación, separe el marco de datos en variables de predicción y respuesta. Separe esos datos en datos de prueba y de entrenamiento con el 80% de los datos en el conjunto de entrenamiento y el resto en el conjunto de prueba.


In [52]:
auto.drop(["car_name"], axis=1, inplace=True)

In [53]:
auto.head(2)

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   

   model_year  
0          70  
1          70

In [54]:
X = auto.drop("mpg", axis=1)
X.head()

cylinders  displacement  horse_power  weight  acceleration  model_year
0          8         307.0        130.0    3504          12.0          70
1          8         350.0        165.0    3693          11.5          70
2          8         318.0        150.0    3436          11.0          70
3          8         304.0        150.0    3433          12.0          70
4          8         302.0        140.0    3449          10.5          70

In [55]:
y = auto.mpg
y.head()

0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
Name: mpg, dtype: float64

In [56]:
X.shape

(392, 6)

In [57]:
y.shape

(392,)

In [58]:
X_train, X_test, y_train, y_test = tts(X,y, test_size=0.2)

Now we will the dataset that we processed and peform linear regression on this data to predict the mpg for each vehicle. Initialize the model in the cell below.

In [59]:
linreg2 = LinReg()

In [60]:
linreg2

LinearRegression()

Next, fit the model in the cell below.

In [61]:
linreg2.fit(X_train, y_train)

LinearRegression()

In [62]:
linreg2.coef_

array([-0.53772568,  0.01601532, -0.00821997, -0.00720529,  0.0813632 ,
        0.794258  ])

In [63]:
linreg2.intercept_

-15.96463758926949

# Challenge 3 - Evaluate the Model

the r squared score of a model tells us how much variation is explained by the model. In a typical dataset, most observations differ from the mean. When we create a model, we are trying to generate an equation that will tell us by how much each observation will differ from the mean. Obviously, the vast majority of models are not perfect. They can only predict some of the variation from the mean but not all of it. We attribute the rest of the difference between the actual value and the mean to random error. We would like random error to explain the as little as possible of the variation. This is why the r squared score is an important metric.

In the next cell, compute the r squared score of the model. Do this by first computing the predicted values and assign them to `y_pred`.

In [64]:
from sklearn import metrics
import numpy as np

In [65]:
y_pred = linreg2.predict(X_test)

In [66]:
y_pred.shape

(79,)

In [67]:
print('R2 - Coeficiente de Determinacion', metrics.r2_score(y_test, y_pred))

R2 - Coeficiente de Determinacion 0.7662657572044236


#### Our next step is to evaluate the model using the test data. We would like to ensure that our model is not overfitting the data. This means that our model will not be able to generalize well outside of the training data.

In the cell below, use the model to generate the predicted values for the training data and assign them to `y_test_pred`. Compute the r squared score for the test data by comparing the oberserved `y_test` data and the predicted `y_test_pred`.

In [68]:
y_test_pred = linreg2.predict(X_train)
print('R2 - Coeficiente de Determinacion', metrics.r2_score(y_train, y_test_pred))

R2 - Coeficiente de Determinacion 0.8169528704253226


# Challenge 4 - Improve the Model Fit

While the most common way to improve the fit of a model is by using regularization, there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [69]:
X_train09, X_test09, y_train09, y_test09 = tts(X,y, test_size=0.1)

Initialize a new model. Name this model `auto_model09`. Fit the model to the new sample data.

In [70]:
auto_model09 = LinReg()

In [71]:
auto_model09.fit(X_train09, y_train09)

LinearRegression()

In [72]:
auto_model09.coef_

array([-0.36282542,  0.00854982, -0.00124042, -0.00679963,  0.06776965,
        0.75047162])

In [73]:
auto_model09.intercept_

-13.941037120073975

Compute the predicted values and r squared score for our new model and new sample data.

In [74]:
y_pred09 = auto_model09.predict(X_test09)

In [75]:
y_pred09.shape

(40,)

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [76]:
print('R2 - Coeficiente de Determinacion', metrics.r2_score(y_test09, y_pred09))

R2 - Coeficiente de Determinacion 0.7659484115364349


### Yes, there is an improvement of 0.03 points over the results of the previous sample.

# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

In [77]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [78]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=3, step=1)
selector = selector.fit(X_test, y_test)
selector.support_

array([ True, False, False, False,  True,  True])

Fit the model and print the ranking

In [79]:
selector.ranking_

array([1, 2, 3, 4, 1, 1])

In [80]:
auto.head(1)

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   

   model_year  
0          70

Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [82]:
nuevo_auto = auto[["mpg","cylinders", "acceleration", "model_year"]]

In [83]:
X = nuevo_auto.drop("mpg", axis=1)
X.head()

cylinders  acceleration  model_year
0          8          12.0          70
1          8          11.5          70
2          8          11.0          70
3          8          12.0          70
4          8          10.5          70

In [84]:
y = nuevo_auto.mpg
y.head()

0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
Name: mpg, dtype: float64

In [85]:
X.shape

(392, 3)

In [86]:
y.shape

(392,)

In [87]:
X_train_reduced, X_test_reduced, y_train_reduced, y_test_reduced = tts(X,y, test_size=0.2)

Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [89]:
auto_model_reduced =LinReg()

In [90]:
auto_model_reduced.fit(X_train_reduced, y_train_reduced)

LinearRegression()

In [91]:
auto_model_reduced.coef_

array([-2.96970635, -0.00527948,  0.80955778])

In [92]:
auto_model_reduced.intercept_

-21.753244873884366

In [93]:
y_pred_reduce = auto_model_reduced.predict(X_test_reduced)

In [ ]:
y_pred09.shape